name: autodqm-ml-luck
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyaml
  - uproot
  - numpy
  - xrootd
  - rich
  - pandas
  - pyarrow
  - scipy
  - matplotlib
  - tqdm
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - yahist
    - tensorflow=2.5
